#cloud-config
merge_how: dict(recurse_array)+list(append)
write_files:
  - path: /etc/default/heat-params
    owner: "root:root"
    permissions: "0600"
    content: |
      PROMETHEUS_MONITORING="$PROMETHEUS_MONITORING"
      KUBE_API_PUBLIC_ADDRESS="$KUBE_API_PUBLIC_ADDRESS"
      KUBE_API_PRIVATE_ADDRESS="$KUBE_API_PRIVATE_ADDRESS"
      KUBE_API_PORT="$KUBE_API_PORT"
      KUBE_NODE_PUBLIC_IP="$KUBE_NODE_PUBLIC_IP"
      KUBE_NODE_IP="$KUBE_NODE_IP"
      KUBE_ALLOW_PRIV="$KUBE_ALLOW_PRIV"
      ENABLE_CINDER="$ENABLE_CINDER"
      ETCD_VOLUME="$ETCD_VOLUME"
      ETCD_VOLUME_SIZE="$ETCD_VOLUME_SIZE"
      DOCKER_VOLUME="$DOCKER_VOLUME"
      DOCKER_VOLUME_SIZE="$DOCKER_VOLUME_SIZE"
      DOCKER_STORAGE_DRIVER="$DOCKER_STORAGE_DRIVER"
      NETWORK_DRIVER="$NETWORK_DRIVER"
      FLANNEL_NETWORK_CIDR="$FLANNEL_NETWORK_CIDR"
      FLANNEL_NETWORK_SUBNETLEN="$FLANNEL_NETWORK_SUBNETLEN"
      FLANNEL_BACKEND="$FLANNEL_BACKEND"
      PODS_NETWORK_CIDR="$PODS_NETWORK_CIDR"
      PORTAL_NETWORK_CIDR="$PORTAL_NETWORK_CIDR"
      ADMISSION_CONTROL_LIST="$ADMISSION_CONTROL_LIST"
      ETCD_DISCOVERY_URL="$ETCD_DISCOVERY_URL"
      USERNAME="$USERNAME"
      PASSWORD="$PASSWORD"
      CLUSTER_SUBNET="$CLUSTER_SUBNET"
      TLS_DISABLED="$TLS_DISABLED"
      KUBE_DASHBOARD_ENABLED="$KUBE_DASHBOARD_ENABLED"
      INFLUX_GRAFANA_DASHBOARD_ENABLED="$INFLUX_GRAFANA_DASHBOARD_ENABLED"
      VERIFY_CA="$VERIFY_CA"
      CLUSTER_UUID="$CLUSTER_UUID"
      MAGNUM_URL="$MAGNUM_URL"
      VOLUME_DRIVER="$VOLUME_DRIVER"
      HTTP_PROXY="$HTTP_PROXY"
      HTTPS_PROXY="$HTTPS_PROXY"
      NO_PROXY="$NO_PROXY"
      WAIT_CURL="$WAIT_CURL"
      KUBE_TAG="$KUBE_TAG"
      ETCD_TAG="$ETCD_TAG"
      KUBE_VERSION="$KUBE_VERSION"
      KUBE_DASHBOARD_VERSION="$KUBE_DASHBOARD_VERSION"
      TRUSTEE_USER_ID="$TRUSTEE_USER_ID"
      TRUSTEE_PASSWORD="$TRUSTEE_PASSWORD"
      TRUST_ID="$TRUST_ID"
      AUTH_URL="$AUTH_URL"
      INSECURE_REGISTRY_URL="$INSECURE_REGISTRY_URL"
      CONTAINER_INFRA_PREFIX="$CONTAINER_INFRA_PREFIX"
      SYSTEM_PODS_INITIAL_DELAY="$SYSTEM_PODS_INITIAL_DELAY"
      SYSTEM_PODS_TIMEOUT="$SYSTEM_PODS_TIMEOUT"
      ETCD_LB_VIP="$ETCD_LB_VIP"
      DNS_SERVICE_IP="$DNS_SERVICE_IP"
      DNS_CLUSTER_DOMAIN="$DNS_CLUSTER_DOMAIN"
      CERT_MANAGER_API="$CERT_MANAGER_API"
      CA_KEY="$CA_KEY"
      CALICO_TAG="$CALICO_TAG"
      CALICO_CNI_TAG="$CALICO_CNI_TAG"
      CALICO_KUBE_CONTROLLERS_TAG="$CALICO_KUBE_CONTROLLERS_TAG"
      CALICO_IPV4POOL="$CALICO_IPV4POOL"
      INGRESS_CONTROLLER="$INGRESS_CONTROLLER"
      INGRESS_CONTROLLER_ROLE="$INGRESS_CONTROLLER_ROLE"
      KUBELET_OPTIONS="$KUBELET_OPTIONS"
      KUBECONTROLLER_OPTIONS="$KUBECONTROLLER_OPTIONS"
      KUBEAPI_OPTIONS="$KUBEAPI_OPTIONS"
      KUBEPROXY_OPTIONS="$KUBEPROXY_OPTIONS"
      KUBESCHEDULER_OPTIONS="$KUBESCHEDULER_OPTIONS"
      KUBE_NODE_IPV6="$KUBE_NODE_IPV6"
